user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzgwOTI=

session:
  key: 12345678901234567890123456789012
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


